version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: cluster_cookie
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - login_to_access_page
networks:
  login_to_access_page:
    driver: bridge
